
CREATE TABLE SCORE_INFO(
	STU_NUM INT PRIMARY KEY
	, STU_NAME VARCHAR(50)
	, KOR_SCORE INT
	, ENG_SCORE INT
	, INTRO VARCHAR(100)
	
);

INSERT INTO SCORE_INFO
VALUES(1,'고길동',80,90,'둘리 네이놈!');
DELETE FROM SCORE_INFO;

SELECT * FROM score_info;

INSERT INTO SCORE_INFO
VALUES(1,'고길동',80,90,'둘리 네이놈!');


SELECT STU_NUM
      ,STU_NAME
      ,KOR_SCORE
      ,ENG_SCORE
      ,INTRO
FROM score_info;
WHERE STU_NUM = 1;
