



-- 프로젝트3 번재 수주 프로그램


-- 상품 테이블(PK, UNIQUE(이름), 가격, 규격, 공급자, 주의사항)
CREATE TABLE supply(
	SUPPLY_NUM INT PRIMARY KEY AUTO_INCREMENT NOT NULL
	, SUPPLY_NAME VARCHAR(30) UNIQUE NOT NULL
	, SUPPLY_PRICE INT NOT NULL
	, SUPPLY_STANDARD VARCHAR(50) NOT NULL
	, SUPPLIER VARCHAR(50) NOT NULL
	, SUPPLY_CAUTION VARCHAR(50) NOT NULL
);

-- 고객 테이블(PK, 고객번호, 회사명, 대표명, 주소, 전화번호, 이메일, 기타사항)
CREATE TABLE customer(
	CUSTOMER_NUM INT PRIMARY KEY AUTO_INCREMENT NOT NULL
	, CUSTOMER_LI INT
	, CUSTOMER_NAME VARCHAR(50) NOT NULL
	, CUSTOMER_HEAD_NAME VARCHAR(50) NOT NULL
	, CUSTOMER_ADDRESS VARCHAR(100) NOT NULL
	, CUSTOMER_TEL VARCHAR(50) NOT NULL
	, CUSTOMER_EMAIL VARCHAR(50)
	, CUSTOMER_ETC VARCHAR(100)
);

-- 상품 상세 테이블(PK, FK(상품 번호), 입고 날짜, 입고량)
CREATE TABLE contract(
	CONTRACT_NUM INT PRIMARY KEY AUTO_INCREMENT NOT NULL
	, SUPPLY_NUM INT REFERENCES supply(SUPPLY_NUM) ON DELETE CASCADE
	, CONTRACT_DATE DATE DEFAULT CURRENT_DATE
	, CONTRACT_AMOUNT INT NOT NULL
);

SELECT * FROM CONTRACT

-- 동일한 상품 번호(SUPPLY_NUM)와 입고 날짜(CONTRACT_DATE)에 대한 중복 방지를 위해 UNIQUE 제약 추가
ALTER TABLE CONTRACT
ADD CONSTRAINT UNIQUE_CONTRACT UNIQUE (CONTRACT_DATE, SUPPLY_NUM);

-- 주문 상세 테이블(PK, FK(주문 번호), FK(상품 번호), 주문된 상품 수,) 
CREATE TABLE DETAIL_ORDER_FORM(
	DETAIL_ORDER_NUM INT PRIMARY KEY AUTO_INCREMENT NOT NULL
	, ORDER_NUM INT NOT NULL REFERENCES order_form(ORDER_NUM) ON DELETE CASCADE
	, SUPPLY_NUM INT NOT NULL REFERENCES supply(SUPPLY_NUM) ON DELETE CASCADE
	, ORDER_AMOUNT INT NOT NULL
	, TOTAL_PRICE INT 
);

-- 주문 테이블(PK, FK(고객 번호), 주문 처리 상태, 총 주문 금액, 주문 날짜, 주문 처리자)
CREATE TABLE order_form(
	ORDER_NUM INT PRIMARY KEY AUTO_INCREMENT NOT NULL
	, CUSTOMER_NUM INT NOT NULL REFERENCES customer(CUSTOMER_NUM) ON DELETE CASCADE
	, ORDER_STATUS VARCHAR(50) DEFAULT 'NONE'
	, TOTAL_AMOUNT INT 
	, ORDER_DATE VARCHAR(50) NOT NULL
	, ORDER_MANAGER VARCHAR(50) NOT NULL
);

-- 처리된 주문서 테이블(PK, FK(주문번호), 처리날짜, 처리자)
CREATE TABLE done_form(
	DONE_NUM INT PRIMARY KEY AUTO_INCREMENT NOT NULL
	, ORDER_NUM INT NOT NULL REFERENCES order_form(ORDER_NUM) ON DELETE CASCADE
	, DONE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP
	, DONE_MANAGER VARCHAR(50) NOT NULL
);


-- 재고가 부족한 상품을 담을 테이블(PK, FK(상품번호, 부족했던 주문에 대한 주문번호), 필요 상태, 주문 상태, 얼마나 부족한지 담을 변수, 총 얼마가 부족한지 담을 변수)
CREATE TABLE NEED_FORM(
	NEED_NUM INT PRIMARY KEY AUTO_INCREMENT NOT NULL
	, SUPPLY_NUM INT REFERENCES supply(SUPPLY_NUM) ON DELETE CASCADE
	, ORDER_NUM INT REFERENCES order_form(ORDER_NUM) ON DELETE CASCADE
	, NEED_STATUS VARCHAR(50) NOT NULL DEFAULT 'TRUE'
	, RE_STATUS VARCHAR(50) NOT NULL DEFAULT 'NONE'
	, NEED_CNT INT NOT NULL
	, TOTAL_CNT INT 
);

-- 추가 요청한 상품을 담을 테이블(PK, FK(상품번호, 부족번호),  배송 소요 기간(일단위))
CREATE TABLE PLUS_FORM(
	PLUS_NUM INT PRIMARY KEY AUTO_INCREMENT NOT NULL
	, SUPPLY_NUM INT REFERENCES supply(SUPPLY_NUM) ON DELETE CASCADE
	, NEED_NUM INT REFERENCES NEED_FORM(NEED_NUM) ON DELETE CASCADE
	, DUE_DATE VARCHAR(50) NOT NULL
);

// 주문서 등록 쿼리

INSERT INTO order_form
(CUSTOMER_NUM
, ORDER_DATE
, ORDER_MANAGER)
VALUES
(4
, '2024-07-21'
, '232'
);

// 주문서 상세 정보 등록 쿼리

INSERT INTO detail_order_form
(ORDER_NUM
, SUPPLY_NUM
, ORDER_AMOUNT
)
VALUES
(69
, 1
, 100
);

INSERT INTO detail_order_form
(ORDER_NUM
, SUPPLY_NUM
, ORDER_AMOUNT
)
VALUES
(69
, 3
, 150
);