CREATE TABLE SUPPLY(
SUPPLY_NUM INT PRIMARY KEY AUTO_INCREMENT,
SUPPLY_NAME VARCHAR(30) NOT NULL UNIQUE,
SUPPLY_PRICE INT NOT NULL,
SUPPLY_STANDARD VARCHAR(50),
SUPPLIER VARCHAR(50) NOT NULL,
SUPPLY_CAUTION VARCHAR(50),
SUPPLY_IMAGE VARCHAR(100),
SUPPLY_AMOUNT INT DEFAULT 0,
SUPPLY_MIN_AMOUNT INT DEFAULT 0
);
-- 발주 정보(주문번호, 발주자, 발주일, 배송 날짜, 발주 메모) => 발주 내역이나 발주 시에 입력할 데이터 등
CREATE TABLE ORDER_INFO(
ORDER_NUM INT PRIMARY KEY AUTO_INCREMENT,
ORDER_MANAGER VARCHAR(30) NOT NULL,
ORDER_DATE DATE NOT NULL DEFAULT CURRENT_TIMESTAMP,
DELIVERY_DATE DATE,
ORDER_NOTE VARCHAR(50),
ORDER_STATUS VARCHAR(30) NOT NULL DEFAULT('배송 중')
);
-- 발주 할 물품 목록을 담아 둘 테이블(pk(구분용), 주문할 물품, 각 물품별 주문량, 주문번호)
CREATE TABLE ORDER_SUPPLY_INFO(
ORDER_SUPPLY_NUM INT PRIMARY KEY AUTO_INCREMENT,
SUPPLY_NUM INT REFERENCES SUPPLY(SUPPLY_NUM) ON DELETE CASCADE,
ORDER_AMOUNT INT NOT NULL,
ORDER_NUM INT REFERENCES order_info(ORDER_NUM) ON DELETE CASCADE
);