
DROP TABLE react_bpard;
-- REACT 기본 게시판 프로젝트

CREATE TABLE REACT_BOARD (

	BOARD_NUM INT AUTO_INCREMENT PRIMARY KEY -- AUTO_INCREMENT : 자동으로 증가가 됨
	,BOARD_TITLE VARCHAR(50) NOT NULL
	,BOARD_CONTENT VARCHAR(100)
	,BOARD_WRITER VARCHAR(30) NOT NULL
	,CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP -- DEFAULT가 들어가있어서 없어도 알아서 데이터 들어감! ㄴ
											-- 자동완성으로 키셈;
	-- DATETIME : 시분초까지 다나옴;
);

SELECT * FROM REACT_BOARD;

INSERT INTO REACT_BOARD(
	BOARD_TITLE
	, BOARD_WRITER
) VALUES (
	'두번째 게시글'
	, '김자바'
);


SELECT BOARD_NUM
	, BOARD_TITLE
	, BOARD_WRITER
	, CREATE_DATE
FROM REACT_BOARD;


SELECT BOARD_NUM
	, BOARD_TITLE
	, BOARD_CONTENT
	, BOARD_WRITER
	, CREATE_DATE
FROM react_board;
WHERE BOARD_NUM = 1;




CREATE TABLE REACT_STUDENT (
	
	STU_NUM INT AUTO_INCREMENT PRIMARY KEY
	, STU_NAME VARCHAR(30) NOT NULL
	, KOR_SCORE INT
	, ENG_SCORE INT
	, MATH_SCORE INT
	, STU_AGE INT
	, STU_TEL VARCHAR(20) UNIQUE -- < 중복안되게  010-0000-0000
	, STU_ADDR VARCHAR(50)
	
);

INSERT INTO react_student(STU_NAME,KOR_SCORE,ENG_SCORE,MATH_SCORE) -- 아무것도 안넣으면 자동으로 NULL들어감 ㅎ
VALUES('박연습',50,60,70);

SELECT * FROM react_student;

DELETE



SELECT STU_NUM
	, STU_NAME
	, KOR_SCORE
	, ENG_SCORE
	, MATH_SCORE
	, (KOR_SCORE + ENG_SCORE + MATH_SCORE) / 3 AS AVG-- 평균구하는
FROM react_student;


