

DROP TABLE CAR_INFO;
-- 자동차 정보 관리 테이블
DROP FROM CAR_INFO;

CREATE TABLE CAR_INFO(

	PK_NUM INT AUTO_INCREAMENT PRIMARY KEY
	, CAR_NAME VARCHAR(50) NOT NULL -- 자동차 모델명
	, CAR_PRICE INT NOT NULL -- 자동차 금액
	, CAR_BRAND VARCHAR(50) NOT NULL -- 자동차 제조사
);

SELECT * FROM CAR_INFO;




-- 자동차 구매 관리 테이블

CREATE TABLE SALES_INFO(

	PK_NUM INT AUTO_INCREAMENT PRIMARY KEY -- 판매번호
	, BUYER VARCHAR(50) NOT NULL -- 구매자
	, BUYER_TEL INT -- 구매자 연락처
	, COLOR VARCHAR(50) NOT NULL -- 자동차 색상
	, BUY_DATE DATETIME DEFAULT CURRENT_TIMESTAMP -- 판매일
	, FK_NUM INT NOT NULL -- 모델번호
);




