


CREATE TABLE PAT_TEMP (
   TEMP_NUM INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
   TEMP float,
   TEMP_DATE DATETIME DEFAULT CURRENT_TIMESTAMP
);


INSERT INTO pat_temp(TEMP) VALUES('40');
SELECT * FROM pat_temp;

GRANT ALL PRIVILEGES ON *.* TO 'team1_user'@'192.168.%' IDENTIFIED BY 'mariadb';
